### ISSUE TITLE
No longer works - needs python 3.8+?

### ISSUE THREAD

**Issue by Catchwa** [Unmanic/unmanic-windows-launcher#11]
Application version: Version: 0.2.8+925008e+dirty
Processing fails - error message

```
2024-08-30T22:39:40:INFO:Unmanic.andrew-localhost-Worker-1 - [FORMATTED] - Picked up job - C:\Users\Andrew\AppData\Local\Temp\Unmanic\remote_library\unmanic_remote_pending_library-1725022967.0843408\REDACTED.mkv

2024-08-30T22:39:41:ERROR:Unmanic.andrew-localhost-Worker-1 - [FORMATTED] - Exception in processing job with andrew-localhost-Worker-1: - module 'shlex' has no attribute 'join'

Traceback (most recent call last):

  File "C:\Users\Andrew\AppData\Local\Programs\UnmanicLauncher\Python\lib\site-packages\unmanic\libs\workers.py", line 124, in run

    self.__process_task_queue_item()

  File "C:\Users\Andrew\AppData\Local\Programs\UnmanicLauncher\Python\lib\site-packages\unmanic\libs\workers.py", line 228, in __process_task_queue_item

    success = self.__exec_worker_runners_on_set_task()

  File "C:\Users\Andrew\AppData\Local\Programs\UnmanicLauncher\Python\lib\site-packages\unmanic\libs\workers.py", line 382, in __exec_worker_runners_on_set_task

    success = self.__exec_command_subprocess(data)

  File "C:\Users\Andrew\AppData\Local\Programs\UnmanicLauncher\Python\lib\site-packages\unmanic\libs\workers.py", line 570, in __exec_command_subprocess

    command_string = shlex.join(exec_command)

AttributeError: module 'shlex' has no attribute 'join'

2024-08-30T22:39:42:INFO:Unmanic.andrew-localhost-Worker-1 - [FORMATTED] - Picked up job - C:\Users\Andrew\AppData\Local\Temp\Unmanic\remote_library\unmanic_remote_pending_library-1725022967.0843408\REDACTED.mkv
```

Issue seems similar to https://github.com/k4yt3x/video2x/issues/227

**Comment by Josh5** [comment]
I've put together some fixes, but they need further testing before the changes hit the master branches.
You can test the new builds with the new ffmpeg and python 3.12, but you will need to select the "beta" channel for updates.

**Comment by Catchwa** [comment]
Thanks, I tried that but it seems like it's still using an old Python version?

![image](https://github.com/user-attachments/assets/8f5d4f67-58ae-405f-881f-3adec0b0d60d)

**Comment by Josh5** [comment]
You must be still using the old version of the launcher. Uninstall it and install this new one. This is definitely being shipped with Python 3.12.

**Comment by Catchwa** [comment]
Ok, uninstalled the launcher, downloaded the latest release (that was created yesterday). Tried to download from the beta channel after launching and this is the error message:

![image](https://github.com/user-attachments/assets/3724f55e-6613-47e3-9d83-f066150b5aaf)

**Comment by Josh5** [comment]
Install nodejs

**Comment by Catchwa** [comment]
There's a node installation as part of the Launcher though? In AppData\Local\Programs\UnmanicLauncher\node ?

Anyway, Node is already installed locally. I upgraded to the latest Node LTS and the same error.

**Comment by Catchwa** [comment]
Just revisiting this - I'm using nodejs 20.17.0. Is there a particular version I should use?
Is there a better way for me to gather logs from the failed build, other than to take screenshots of the output window?
Thanks.

**Comment by Josh5** [comment]
Does the beta branch work?

**Comment by Catchwa** [comment]
No, same error message as my last screenshot where it can't copy the woff file

**Comment by Tethgar** [comment]
I'm having the same issue with update not working

**Comment by Catchwa** [comment]
@Josh5  what can I do to help debug this issue?

**Comment by Josh5** [comment]
I think it just needs development effort. Set up a dev env and try a few different things.
